---
name: close-issues-and-mrs

on:
  schedule:
    - cron: 45 21 * * FRI

permissions: {}

jobs:
  close-issues-and-mrs:
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    uses: andreygrechin/github-actions/.github/workflows/close-issues-and-mrs.yml@2920bcbd41f31201daaf7b42868cfc348e5a3de2 # v1.0.0
