---
name: golang-security

on:
  schedule:
    - cron: 45 21 * * FRI

permissions: {}

jobs:
  golang-security:
    permissions:
      contents: read
      pull-requests: read
    uses: andreygrechin/github-actions/.github/workflows/golang-security.yml@main
